### ISSUE TITLE
odbc pop some errors by the prepareStatement to batch insert into table values

### ISSUE THREAD

**Issue by pzhu1015** [SAP/odbc-cpp-wrapper#17]
my connectionstring is : "Driver={MySQL ODBC 5.3 Unicode Driver};Server=127.0.0.1;Port=3306;Database=test;User=root;Password=root;Option=67108864;CharSet=utf8mb4;stmt=SET NAMES utf8mb4;"

m_odbc_connection->setAutoCommit(false);
std::string str = "INSERT INTO T(A,B) VALUES (?,?)";
auto statement = m_odbc_connection->prepareStatement(str.data());
statement->setInt(1, 1);
statement->setString(2, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");//more than 32 char，it's an error
statement->addBatch();
statement->setInt(1, 1);
statement->setString(2, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
statement->addBatch();
statement->executeBatch();
m_odbc_connection->commit();

pop errors: ERROR: 0: HYC00 : [MySQL][ODBC 5.3(w) Driver][mysqld-5.7.29]Parameter arrays with data at execution are not supported

**Comment by pzhu1015** [comment]
When the character length of setString (2, "XXX...") exceeds 32 bytes (INPLACE_BYTES). When the data is put on the heap, the batch operation will make an error. I try to enlarge INPLACE_BYTES can solve this problem, but it is impossible to enlarge infinitely. After all, the stack space is limited. Please help to see if there is a problem in the organization of heap memory data structure

**Comment by stefanuhrig** [comment]
Hi @pzhu1015,

I tested batch inserts on different databases.

Unfortunately, there are many ODBC drivers that don't support variable sized data in batch inserts (i.e. `SQLExecute` with additional `SQLPutData` calls or "data at execution" as it's called by the MySQL ODBC driver).

The batch inserts worked with PostgreSQL and SAP HANA, but did not work with MySQL, MariaDB and MS SQL.

As the error message you are receiving points out, this feature seems not to be implemented in the MySQL ODBC driver.

As a workaround, you can use single inserts (i.e. use `statement->executeUpdate()` instead of `statement->addBatch()`). Performance is likely not as good as with batch inserts though.

As the issue seems to be with the ODBC driver and not within the wrapper, I'll close the issue.
